main:
  - name: About
    url: '/#about'
    weight: 10
  - name: Research
    url: '/#research'
    weight: 20
  - name: Venture
    url: '/#venture'
    weight: 30
#  - name: Publications
#    url: '/#publications'
#    weight: 40
  - name: Projects
    url: '/#projects'
    weight: 50
  - name: Talks
    url: '/#talks'
    weight: 60
  - name: CV
    url: uploads/cv.pdf
    weight: 70
  - name: Contact
    url: '/#contact'
    weight: 80
